### ISSUE TITLE
Could not find artefact

### ISSUE THREAD

**Issue by McPringle** [grimmjo/jaxrs-analyzer-gradle-plugin#1]
When I follow your README file and start the build afterward, I get the following error message:

```
$ ./gradlew assemble

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'randomuser'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.grimmjo:jaxrs-analyser-gradle-plugin:0.1-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1-SNAPSHOT/jaxrs-analyser-gradle-plugin-0.1-SNAPSHOT.pom
       - https://jcenter.bintray.com/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1-SNAPSHOT/jaxrs-analyser-gradle-plugin-0.1-SNAPSHOT.jar
       - https://repo.maven.apache.org/maven2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1-SNAPSHOT/jaxrs-analyser-gradle-plugin-0.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1-SNAPSHOT/jaxrs-analyser-gradle-plugin-0.1-SNAPSHOT.jar
       - https://plugins.gradle.org/m2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1-SNAPSHOT/maven-metadata.xml
       - https://plugins.gradle.org/m2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1-SNAPSHOT/jaxrs-analyser-gradle-plugin-0.1-SNAPSHOT.pom
       - https://plugins.gradle.org/m2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1-SNAPSHOT/jaxrs-analyser-gradle-plugin-0.1-SNAPSHOT.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

**Comment by grimmjo** [comment]
Hey,

I'm gonna release it in the next few days on bintray and mavens central..
Need to add ci pipeline

**Comment by torniketar** [comment]
Hello, any updates when it will be available? :)

> Could not find com.github.grimmjo:jaxrs-analyser-gradle-plugin:0.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1/jaxrs-analyser-gradle-plugin-0.1.pom
       - https://repo.maven.apache.org/maven2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1/jaxrs-analyser-gradle-plugin-0.1.jar
       - https://plugins.gradle.org/m2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1/jaxrs-analyser-gradle-plugin-0.1.pom
       - https://plugins.gradle.org/m2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1/jaxrs-analyser-gradle-plugin-0.1.jar

**Comment by grimmjo** [comment]
Hi @torniketar,

it's already available in the bintray repository.
Here is the code snippet.
``
repositories {
    maven { 
        url  "https://dl.bintray.com/grimmjo/maven-releases" 
    }
}
``

I'm just waiting for the Bintray team to confirm the package. Then I can add it to Jcenter and syn itc to Maven Central

**Comment by torniketar** [comment]
@grimmjo  Thanks for fast response.
unfortunately still getting next error:
> Could not find com.github.grimmjo:jaxrs-analyser-gradle-plugin:0.1.
     Searched in the following locations:
       - https://dl.bintray.com/grimmjo/maven-releases/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1/jaxrs-analyser-gradle-plugin-0.1.pom
       - https://dl.bintray.com/grimmjo/maven-releases/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1/jaxrs-analyser-gradle-plugin-0.1.jar
       - https://plugins.gradle.org/m2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1/jaxrs-analyser-gradle-plugin-0.1.pom
       - https://plugins.gradle.org/m2/com/github/grimmjo/jaxrs-analyser-gradle-plugin/0.1/jaxrs-analyser-gradle-plugin-0.1.jar
     



maybe i have something wrong in grade.build :

buildscript {
    dependencies {

        classpath 'com.github.grimmjo:jaxrs-analyser-gradle-plugin:0.1'
    }

    repositories {
        maven { url "https://dl.bintray.com/grimmjo/maven-releases" }
      //  mavenCentral()

    }


}

plugins {
    id 'war'
}

group 'com.mycompany'
version '1.0'
sourceCompatibility = 1.8



repositories {
        mavenCentral()
    }

dependencies {
        testCompile group: 'junit', name: 'junit', version: '4.12'

        compileOnly group: 'javax.servlet', name: 'javax.servlet-api', version: '3.1.0'
        compileOnly group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: '2.1'
        compileOnly group: 'javax.websocket', name: 'javax.websocket-api', version: '1.1'


    }

war {
    webInf { from 'src/main/resources' }
    webXml = file('src/main/webapp/WEB-INF/web.xml')
}

**Comment by grimmjo** [comment]
@torniketar 
Finally found the problem.. just a spelling mistake

`classpath com.github.grimmjo:jaxrs-analyzer-gradle-plugin:0.1`
Download is also possible with maven and jcenter.
Could you please verify it and leave a comment here? Thank you

**Comment by torniketar** [comment]
Great, Thank you. worked both versions. build successful:) in my case jaxrs-analyzer wasn't created, tried to manually create folder inside build but nothing appeared after build. will take a look again on instructions.

**Comment by grimmjo** [comment]
Oke I will close this issue then.. have u tried just running the task. Just open a new issue if you have further problems.. 
Sorry for all the problems, this is my first open source released project.
