### ISSUE TITLE
Detailed Implementation guide or video Tutorial/

### ISSUE THREAD

**Issue by torniketar** [grimmjo/jaxrs-analyzer-gradle-plugin#2]
Greetings.
At first thanks for your job.
trying to use your plugin but have some issues with integrations.

modified my build.gradle file like that:

buildscript {
    dependencies {

        classpath 'com.github.grimmjo:jaxrs-analyzer-gradle-plugin:0.1'
    }

    repositories {
        mavenCentral()
        jcenter()
    }
}

plugins {
    id 'war'
}

group 'com.my.company'
version '1.0'
sourceCompatibility = 1.8

repositories {
        mavenCentral()
}

dependencies {
        testCompile group: 'junit', name: 'junit', version: '4.12'

        compileOnly group: 'javax.servlet', name: 'javax.servlet-api', version: '3.1.0'
        compileOnly group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: '2.1'
        compileOnly group: 'javax.websocket', name: 'javax.websocket-api', version: '1.1'

    }

war {
    webInf { from 'src/main/resources' }
    webXml = file('src/main/webapp/WEB-INF/web.xml')
}

gradle build was successful but into build folder isn't created jaxrs-alayzer folder.
please help is there something missing into my project or what should i do.
Thanks in advance.

**Comment by grimmjo** [comment]
Hi @torniketar,

sorry for the late response. I just released a new version and added a example [JAX-RS Analyzer Gradle Plugin Samples](https://github.com/grimmjo/jaxrs-analyzer-gradle-plugin-samples)

If you have further problems, just open a new issue ;)
