### ISSUE TITLE
Can't make the plugin working

### ISSUE THREAD

**Issue by Nindouja** [grimmjo/jaxrs-analyzer-gradle-plugin#3]
Hello, 

I've got trouble making your plugin work... It might be a silly problem but I'm not a gradle expert...

So when i try apply your plugin on my Java project I got an error message error on build `No such property: outputDir for class: org.gradle.api.internal.file.DefaultSourceDirectorySet`.

I was first trying to apply it to a kotlin project but there it did nothing; no error; no output. I dont even know if it run.

So could you explain:

* first; does the plugin should work with kotlin project ? I think it should as I'm using the same annotations; and i think i've read on the author blog that jaxRsAnalyzer that it was analyzing the bytecode and not the raw code
* second; the errr I got on the java project; is it revelant to you ? Is it possible it is a bug or u think i certainly misconfigure slth ?

Anyway thanks for the time you put into this plugin and you'll put replying to this. Awesome work :D

**Comment by grimmjo** [comment]
Hi @BancarelValentin,
Can you provide me some more information? Like gradle version, java version and if possible your build.gradle file or the log output of gradle..  
I'll investigate this as soon as possible.

**Comment by Nindouja** [comment]
__[UPDATE]__ i edited the `build.gradle` of this comment as explained in another comment below.


Yes of course; here you go:


Gradle: `Gradle 3.5-rc-2.`


My build output: 
```
10:09:17: Executing task 'build'...


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Programmation\workspaces\HFR\api\build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'api'.
> Failed to apply plugin [id 'jaxrs-analyzer-gradle-plugin']
   > No such property: outputDir for class: org.gradle.api.internal.file.DefaultSourceDirectorySet

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.132 secs
No such property: outputDir for class: org.gradle.api.internal.file.DefaultSourceDirectorySet
10:09:17: Task execution finished 'build'.
```

My `build.gradle` file
```
group 'superavenir'
wrapper.gradleVersion = '4.10'

buildscript {
    ext.kotlin_version = '1.2.41'

    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.github.grimmjo:jaxrs-analyzer-gradle-plugin:0.2'
    }
}

apply plugin: 'idea'
apply plugin: 'war'
apply plugin: 'kotlin'
apply plugin: "jaxrs-analyzer-gradle-plugin"

sourceCompatibility = 1.8

repositories {
    maven {
        url "https://repository.jboss.org/nexus/content/repositories/releases/"
    }
    maven {
        url "https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/"
    }
    mavenCentral()
}

dependencies {

    compile 'org.json:json:20170516'

    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"

    compileOnly 'javax.ejb:javax.ejb-api:3.2'
    compileOnly 'javax.inject:javax.inject:1'
    compileOnly 'javax.ws.rs:javax.ws.rs-api:2.0.1'
    compileOnly 'javax.websocket:javax.websocket-api:1.1'
    compileOnly 'javax.enterprise:cdi-api:1.2'
    compileOnly 'javax.mail:mail:1.4.7'
    compileOnly 'javax.servlet:javax.servlet-api:3.1.0'
    compileOnly 'org.jboss.resteasy:resteasy-multipart-provider:3.1.2.Final'
    compileOnly 'org.jboss.ejb3:jboss-ejb3-ext-api:2.2.0.Final'

    //compile 'org.wildfly:wildfly-clustering-infinispan:10.1.0.Final'
    //compileOnly 'org.wildfly:wildfly-clustering-infinispan-spi:10.1.0.Final'
    compileOnly 'org.wildfly:wildfly-clustering-infinispan-extension:10.1.0.Final'

    compile 'com.ibm.icu:icu4j:51.1'
    compile 'commons-validator:commons-validator:1.4.0'
    compile 'commons-io:commons-io:2.5'
    compile 'org.apache.commons:commons-csv:1.4'
    compile 'org.apache.poi:poi:3.14'
    compile 'org.apache.poi:poi-ooxml:3.14'
    compile 'org.apache.poi:poi-ooxml-schemas:3.14'
    compile 'commons-logging:commons-logging:1.2'
    compile 'commons-codec:commons-codec:1.10'
    compile 'org.apache.commons:commons-collections4:4.1'
    compile 'org.apache.logging.log4j:log4j-core:2.8.1'
    compile 'org.apache.xmlbeans:xmlbeans:2.6.0'
    compile 'log4j:log4j:1.2.16'
    compile 'com.google.guava:guava:24.1-jre'
    compile 'org.apache.httpcomponents:httpmime:4.5.6'
    compile group: 'com.ibm.icu', name: 'icu4j', version: '62.1'
    compile 'com.auth0:java-jwt:3.4.1'// JSON Web token: https://github.com/auth0/java-jwt


    compile files('src/main/resources/DKIMforJavaMail.jar')

    testCompile 'junit:junit:4.12'
}

war {
    manifest {
        attributes("Dependencies": "org.infinispan")
    }
}

jaxRsAnalyzer {
    // Available backends are plaintext, asciidoc and swagger (default)
    backend 'swagger', 'asciidoc'
    // Domain of the deployed project, defaults to ""
    domain 'localhost:8080'
    // Comma separated list of Swagger schemes (only for if backend is swagger, defaults to http)
    schemes 'http', 'https'
    // Enables rendering of Swagger tags (defaults to false -> default tag will be used)
    renderTags true
    // The number at which path position the Swagger tags will be extracted (defaults to 0)
    tagPathOffset 0
    // Directory (relative to buildDir) where resources will be generated (defaults to jaxrs-analyzer)
    outputDirectory 'jaxrs-analyzer'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

**Comment by grimmjo** [comment]
Looks like your gradle version is too old.
Can you upgrade it to a newer version, but at least 4.0? I would recommeny you 4.10.
`./gradlew wrapper --gradle-version=4.10`

**Comment by Nindouja** [comment]
Thanks, i just tried it but doesnt change a lot; does the command set the version just for this run ? Am i not suppose to chande my gradlew executable ?

Here is the output of the command if it helps

`$ ./gradlew wrapper --gradle-version=4.10`
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Programmation\workspaces\HFR\api\build.gradle' line: 19

* What went wrong:
A problem occurred evaluating root project 'api'.
> Failed to apply plugin [id 'jaxrs-analyzer-gradle-plugin']
   > No such property: outputDir for class: org.gradle.api.internal.file.DefaultSourceDirectorySet

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.341 secs
```

__[UPDATE]__ I now have added (as mention [here](https://discuss.gradle.org/t/how-to-update-gradle-wrapper-version-in-buildship/21457)) the folowing line on top of my `build.gradle` file just below the group
`wrapper.gradleVersion = '4.10'`

**Comment by Nindouja** [comment]
Hey, so today I tried again ! After my previous post i did not execute the wrapper task; today i did and the build succeed !

But I still have nothing generated :/

![image](https://user-images.githubusercontent.com/5629639/49510477-a27ad600-f888-11e8-85c0-2d97154524a3.png)

**Comment by grimmjo** [comment]
That looks better.
The plugin is not automatically integrated in the build lifecycle.
Either run `./gradlew analyze` or `./gradlew.bat analyze` 
or put `build.dependsOn analyze` in your `build.gradle` to automatically run it during the build

**Comment by Nindouja** [comment]
Yeah !! Much better. Except that the plugin pass the java classes folder as an input; I'm using kotlin; it is not supported i guess ?

On [this file](https://github.com/grimmjo/jaxrs-analyzer-gradle-plugin/blob/master/src/main/groovy/com/github/grimmjo/jaxrs_analyzer/gradle/JaxRsAnalyzerPlugin.groovy) on line 22; you explicitly give the java output dir. Any way to make this a configuration ?

**Comment by grimmjo** [comment]
I've seen your pull request.. I going to do a rework in the holidays.. it will include gradle 5 support and also groovy and kotlin support.. I will release it asap :)

**Comment by grimmjo** [comment]
Years later, as already mentioned in the pull request, sorry for that.
I migrated the plugin to kotlin and updated to Gradle 8 and Java 17 build as well.

I'll release the 0.4 version today. The only problem is that could not test it 😆 
The plugin id changed from `com.github.grimmjo` to `io.github.grimmjo.jaxrs-analyzer`

If you find any issues, feel free to open a new issue 😉
