### ISSUE TITLE
gradle 7.4.2 requires implementation rather than compile method

### ISSUE THREAD

**Issue by sammyjava** [grimmjo/jaxrs-analyzer-gradle-plugin#8]
There are some compile commands which are now not available in gradle 7.4.2, for example. (I've had to switch lots of build.gradle files over to "implementation", which just seems silly.)
```
What went wrong:
An exception occurred applying plugin request [id: 'com.github.grimmjo', version: '0.3']
> Failed to apply plugin 'com.github.grimmjo'.
   > Could not find method compile() for arguments [com.sebastian-daschner:jaxrs-analyzer:0.17] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler
```
I wonder if you could make your plugin compatible with gradle 7.4.2. Much appreciated!

**Comment by grimmjo** [comment]
Hi @sammyjava,

thank you for updating your pull request.
I migrated the plugin to kotlin and updated to Gradle 8 and Java 17 build as well.

I'll release the 0.4 version today. The only problem is that could not test it 😆
The plugin id changed from com.github.grimmjo to io.github.grimmjo.jaxrs-analyzer

If you find any issues, feel free to open a new issue 😉
